trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: image-generation.yml
  parameters:
    image_type: ubuntuminimal
    image_readme_name: Ubuntu2204-Readme.md